<?php
/**
 * /WWW/yii.mmf-vollies/frontend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var common\models\Application $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="application-form">

	<?php $form = ActiveForm::begin([
		'id' => 'Application',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-danger'
	]
);
?>

	<div class="">
		<?php $this->beginBlock('main'); ?>

		<p>


<!-- attribute user_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\User::find()->all(), 'id', 'id'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
	]
); ?>

<!-- attribute job_choice_1 -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_1')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_1'])),
	]
); ?>

<!-- attribute year -->
			<?php echo $form->field($model, 'year')->textInput(['maxlength' => true]) ?>

<!-- attribute availableFromDate -->
			<?php echo $form->field($model, 'availableFromDate')->textInput(['maxlength' => true]) ?>

<!-- attribute availableFromTime -->
			<?php echo $form->field($model, 'availableFromTime')->textInput() ?>

<!-- attribute availableToDate -->
			<?php echo $form->field($model, 'availableToDate')->textInput(['maxlength' => true]) ?>

<!-- attribute availableToTime -->
			<?php echo $form->field($model, 'availableToTime')->textInput() ?>

<!-- attribute job_choice_2 -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_2')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_2'])),
	]
); ?>

<!-- attribute job_choice_3 -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_3')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_3'])),
	]
); ?>

<!-- attribute bestTIme -->
			<?php echo $form->field($model, 'bestTIme')->textInput() ?>

<!-- attribute double -->
			<?php echo $form->field($model, 'double')->textInput() ?>

<!-- attribute accepted -->
			<?php echo $form->field($model, 'accepted')->textInput() ?>

<!-- attribute team_id -->
			<?php echo $form->field($model, 'team_id')->textInput() ?>

<!-- attribute rejected -->
			<?php echo $form->field($model, 'rejected')->textInput() ?>

<!-- attribute availabilityNotes -->
			<?php echo $form->field($model, 'availabilityNotes')->textarea(['rows' => 6]) ?>

<!-- attribute otherNotes -->
			<?php echo $form->field($model, 'otherNotes')->textarea(['rows' => 6]) ?>

<!-- attribute rejectedReason -->
			<?php echo $form->field($model, 'rejectedReason')->textarea(['rows' => 6]) ?>

<!-- attribute referee -->
			<?php echo $form->field($model, 'referee')->textInput(['maxlength' => true]) ?>

<!-- attribute refereeRelationship -->
			<?php echo $form->field($model, 'refereeRelationship')->textInput(['maxlength' => true]) ?>

<!-- attribute refereePhone -->
			<?php echo $form->field($model, 'refereePhone')->textInput(['maxlength' => true]) ?>
		</p>
		<?php $this->endBlock(); ?>

		<?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'Application'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
		<hr/>

		<?php echo $form->errorSummary($model); ?>

		<?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? 'Create' : 'Save'),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

		<?php ActiveForm::end(); ?>

	</div>

</div>
