<?php
/**
 * /WWW/yii.mmf-vollies/backend/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var common\models\History $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="history-form">

    <?php $form = ActiveForm::begin([
		'id' => 'History',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute user_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(common\models\User::find()->all(), 'id', 'id'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
	]
); ?>

<!-- attribute givenName -->
			<?php echo $form->field($model, 'givenName')->textInput(['maxlength' => true]) ?>

<!-- attribute familyName -->
			<?php echo $form->field($model, 'familyName')->textInput(['maxlength' => true]) ?>

<!-- attribute locality -->
			<?php echo $form->field($model, 'locality')->textInput(['maxlength' => true]) ?>

<!-- attribute emergencyContact -->
			<?php echo $form->field($model, 'emergencyContact')->textInput(['maxlength' => true]) ?>

<!-- attribute emergencyPhone1 -->
			<?php echo $form->field($model, 'emergencyPhone1')->textInput(['maxlength' => true]) ?>

<!-- attribute original_id -->
			<?php echo $form->field($model, 'original_id')->textInput() ?>

<!-- attribute rsa -->
			<?php echo $form->field($model, 'rsa')->textInput() ?>

<!-- attribute dl_c -->
			<?php echo $form->field($model, 'dl_c')->textInput() ?>

<!-- attribute dl_h -->
			<?php echo $form->field($model, 'dl_h')->textInput() ?>

<!-- attribute cse -->
			<?php echo $form->field($model, 'cse')->textInput() ?>

<!-- attribute ohs -->
			<?php echo $form->field($model, 'ohs')->textInput() ?>

<!-- attribute vol -->
			<?php echo $form->field($model, 'vol')->textInput() ?>

<!-- attribute mmfVol -->
			<?php echo $form->field($model, 'mmfVol')->textInput() ?>

<!-- attribute mmfAtt -->
			<?php echo $form->field($model, 'mmfAtt')->textInput() ?>

<!-- attribute returned -->
			<?php echo $form->field($model, 'returned')->textInput() ?>

<!-- attribute preferredJobs -->
			<?php echo $form->field($model, 'preferredJobs')->textarea(['rows' => 6]) ?>

<!-- attribute availability -->
			<?php echo $form->field($model, 'availability')->textarea(['rows' => 6]) ?>

<!-- attribute commentsInformation -->
			<?php echo $form->field($model, 'commentsInformation')->textarea(['rows' => 6]) ?>

<!-- attribute discovery -->
			<?php echo $form->field($model, 'discovery')->textarea(['rows' => 6]) ?>

<!-- attribute created_orig -->
			<?php echo $form->field($model, 'created_orig')->textInput() ?>

<!-- attribute updated_orig -->
			<?php echo $form->field($model, 'updated_orig')->textInput() ?>

<!-- attribute preferredName -->
			<?php echo $form->field($model, 'preferredName')->textInput(['maxlength' => true]) ?>

<!-- attribute country -->
			<?php echo $form->field($model, 'country')->textInput(['maxlength' => true]) ?>

<!-- attribute email -->
			<?php echo $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<!-- attribute phone1 -->
			<?php echo $form->field($model, 'phone1')->textInput(['maxlength' => true]) ?>

<!-- attribute phone2 -->
			<?php echo $form->field($model, 'phone2')->textInput(['maxlength' => true]) ?>

<!-- attribute emergencyPhone2 -->
			<?php echo $form->field($model, 'emergencyPhone2')->textInput(['maxlength' => true]) ?>

<!-- attribute address1 -->
			<?php echo $form->field($model, 'address1')->textInput(['maxlength' => true]) ?>

<!-- attribute address2 -->
			<?php echo $form->field($model, 'address2')->textInput(['maxlength' => true]) ?>

<!-- attribute state -->
			<?php echo $form->field($model, 'state')->textInput(['maxlength' => true]) ?>

<!-- attribute ip -->
			<?php echo $form->field($model, 'ip')->textInput(['maxlength' => true]) ?>

<!-- attribute postcode -->
			<?php echo $form->field($model, 'postcode')->textInput(['maxlength' => true]) ?>

<!-- attribute key_orig -->
			<?php echo $form->field($model, 'key_orig')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => Yii::t('models', 'History'),
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? 'Create' : 'Save'),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
