<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_auth_assignment".
 *
 * @property string $item_name
 * @property string $user_id
 * @property integer $created_at
 *
 * @property \common\models\AuthItem $itemName
 * @property string $aliasModel
 */
abstract class AuthAssignment extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_auth_assignment';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
				'updatedAtAttribute' => false,
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['item_name', 'user_id'], 'required'],
			[['item_name', 'user_id'], 'string', 'max' => 64],
			[['item_name'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AuthItem::className(), 'targetAttribute' => ['item_name' => 'name']]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'item_name' => 'Item Name',
			'user_id' => 'User ID',
			'created_at' => 'Created At',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getItemName()
	{
		return $this->hasOne(\common\models\AuthItem::className(), ['name' => 'item_name']);
	}




}
