<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_job".
 *
 * @property integer $id
 * @property integer $team_id
 * @property integer $sequence
 * @property string $name
 * @property string $menuGroup
 * @property string $description
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\ApplicationJob[] $applicationJobs
 * @property \common\models\Team $team
 * @property string $aliasModel
 */
abstract class Job extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_job';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => BlameableBehavior::className(),
			],
			[
				'class' => TimestampBehavior::className(),
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['team_id', 'sequence', 'name', 'menuGroup'], 'required'],
			[['team_id', 'sequence'], 'integer'],
			[['description'], 'string'],
			[['name', 'menuGroup'], 'string', 'max' => 24],
			[['team_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Team::className(), 'targetAttribute' => ['team_id' => 'id']]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'team_id' => 'Team ID',
			'sequence' => 'Sequence',
			'name' => 'Name',
			'menuGroup' => 'Menu Group',
			'description' => 'Description',
			'created_at' => 'Created At',
			'created_by' => 'Created By',
			'updated_at' => 'Updated At',
			'updated_by' => 'Updated By',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getApplicationJobs()
	{
		return $this->hasMany(\common\models\ApplicationJob::className(), ['job_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getTeam()
	{
		return $this->hasOne(\common\models\Team::className(), ['id' => 'team_id']);
	}




}
