<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_team".
 *
 * @property integer $id
 * @property integer $head_id
 * @property integer $sequence
 * @property string $name
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Job[] $jobs
 * @property \common\models\User $head
 * @property string $aliasModel
 */
abstract class Team extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_team';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['head_id', 'sequence'], 'integer'],
			[['sequence', 'name'], 'required'],
			[['description'], 'string'],
			[['name'], 'string', 'max' => 24],
			[['head_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['head_id' => 'id']]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'head_id' => 'Head ID',
			'sequence' => 'Sequence',
			'name' => 'Name',
			'description' => 'Description',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getJobs()
	{
		return $this->hasMany(\common\models\Job::className(), ['team_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getHead()
	{
		return $this->hasOne(\common\models\User::className(), ['id' => 'head_id']);
	}




}
