<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_user".
 *
 * @property integer $id
 * @property integer $role_id
 * @property integer $status
 * @property string $email
 * @property string $username
 * @property string $password
 * @property string $auth_key
 * @property string $access_token
 * @property string $logged_in_ip
 * @property string $logged_in_at
 * @property string $created_ip
 * @property string $banned_at
 * @property string $banned_reason
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Application[] $applications
 * @property \common\models\Commitment[] $commitments
 * @property \common\models\History[] $histories
 * @property \common\models\Profile $profile
 * @property \common\models\Team[] $teams
 * @property \common\models\Role $role
 * @property \common\models\UserAuth[] $userAuths
 * @property \common\models\UserToken[] $userTokens
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_user';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['role_id', 'status'], 'integer'],
			[['status', 'email', 'password'], 'required'],
			[['logged_in_at', 'banned_at'], 'safe'],
			[['email', 'username', 'password', 'auth_key', 'access_token', 'logged_in_ip', 'created_ip', 'banned_reason'], 'string', 'max' => 255],
			[['email'], 'unique'],
			[['username'], 'unique'],
			[['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Role::className(), 'targetAttribute' => ['role_id' => 'id']]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'role_id' => 'Role ID',
			'status' => 'Status',
			'email' => 'Email',
			'username' => 'Username',
			'password' => 'Password',
			'auth_key' => 'Auth Key',
			'access_token' => 'Access Token',
			'logged_in_ip' => 'Logged In Ip',
			'logged_in_at' => 'Logged In At',
			'created_ip' => 'Created Ip',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
			'banned_at' => 'Banned At',
			'banned_reason' => 'Banned Reason',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getApplications()
	{
		return $this->hasMany(\common\models\Application::className(), ['user_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getCommitments()
	{
		return $this->hasMany(\common\models\Commitment::className(), ['user_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getHistories()
	{
		return $this->hasMany(\common\models\History::className(), ['user_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getProfile()
	{
		return $this->hasOne(\common\models\Profile::className(), ['user_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getTeams()
	{
		return $this->hasMany(\common\models\Team::className(), ['head_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getRole()
	{
		return $this->hasOne(\common\models\Role::className(), ['id' => 'role_id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUserAuths()
	{
		return $this->hasMany(\common\models\UserAuth::className(), ['user_id' => 'id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUserTokens()
	{
		return $this->hasMany(\common\models\UserToken::className(), ['user_id' => 'id']);
	}


	
	/**
	 * @inheritdoc
	 * @return \common\models\UserQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new \common\models\UserQuery(get_called_class());
	}


}
