<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "Application".
 *
 * @property integer $id
 * @property integer $profileId
 * @property integer $preferredJobId1
 * @property integer $preferredJobId2
 * @property integer $preferredJobId3
 * @property string $availableFromDate
 * @property integer $availableFromTime
 * @property string $availableToDate
 * @property integer $availableToTime
 * @property string $availabilityNotes
 * @property string $otherNotes
 * @property string $created
 * @property integer $createdBy
 * @property string $updated
 * @property integer $updatedBy
 * @property string $aliasModel
 */
abstract class Application extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'Application';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'createdBy',
				'updatedByAttribute' => 'updatedBy',
			],
			[
				'class' => TimestampBehavior::className(),
				'createdAtAttribute' => 'created',
				'updatedAtAttribute' => 'updated',
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['profileId', 'preferredJobId1', 'preferredJobId2', 'preferredJobId3', 'availableFromTime', 'availableToTime'], 'integer'],
			[['availableFromDate', 'availableFromTime', 'availableToDate', 'availableToTime'], 'required'],
			[['availableFromDate', 'availableToDate'], 'safe'],
			[['availabilityNotes', 'otherNotes'], 'string']
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'profileId' => 'Profile ID',
			'preferredJobId1' => 'Preferred Job Id1',
			'preferredJobId2' => 'Preferred Job Id2',
			'preferredJobId3' => 'Preferred Job Id3',
			'availableFromDate' => 'Available From Date',
			'availableFromTime' => 'Available From Time',
			'availableToDate' => 'Available To Date',
			'availableToTime' => 'Available To Time',
			'availabilityNotes' => 'Availability Notes',
			'otherNotes' => 'Other Notes',
			'created' => 'Created',
			'createdBy' => 'Created By',
			'updated' => 'Updated',
			'updatedBy' => 'Updated By',
		];
	}


	
	/**
	 * @inheritdoc
	 * @return \common\models\ApplicationQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new \common\models\ApplicationQuery(get_called_class());
	}


}
