<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_commitment".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $application_id
 * @property integer $team_id
 * @property string $year
 * @property string $job
 * @property integer $hours
 * @property string $report
 * @property integer $reinvite
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\Profile $user
 * @property string $aliasModel
 */
abstract class Commitment extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_commitment';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => BlameableBehavior::className(),
			],
			[
				'class' => TimestampBehavior::className(),
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['user_id', 'year', 'job'], 'required'],
			[['user_id', 'application_id', 'team_id', 'hours', 'reinvite'], 'integer'],
			[['year'], 'safe'],
			[['report'], 'string'],
			[['job'], 'string', 'max' => 48],
			[['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Profile::className(), 'targetAttribute' => ['user_id' => 'user_id']]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'user_id' => 'User ID',
			'application_id' => 'Application ID',
			'team_id' => 'Team ID',
			'year' => 'Year',
			'job' => 'Job',
			'hours' => 'Hours',
			'report' => 'Report',
			'reinvite' => 'Reinvite',
			'created_at' => 'Created At',
			'created_by' => 'Created By',
			'updated_at' => 'Updated At',
			'updated_by' => 'Updated By',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUser()
	{
		return $this->hasOne(\common\models\Profile::className(), ['user_id' => 'user_id']);
	}


	
	/**
	 * @inheritdoc
	 * @return \common\models\CommitmentQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new \common\models\CommitmentQuery(get_called_class());
	}


}
