<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "Department".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $created
 * @property integer $createdBy
 * @property string $updated
 * @property integer $updatedBy
 * @property string $aliasModel
 */
abstract class Department extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Department';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'createdBy',
                'updatedByAttribute' => 'updatedBy',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description'], 'string'],
            [['name'], 'string', 'max' => 24],
            [['name'], 'unique'],
            [['name'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'created' => 'Created',
            'createdBy' => 'Created By',
            'updated' => 'Updated',
            'updatedBy' => 'Updated By',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\DepartmentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\DepartmentQuery(get_called_class());
    }


}
