<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mmf_invite".
 *
 * @property integer $id
 * @property string $email
 * @property string $name
 * @property string $password
 * @property integer $role
 * @property string $aliasModel
 */
abstract class Invite extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_invite';
	}


	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['email', 'name', 'password'], 'required'],
			[['role'], 'integer'],
			[['email'], 'string', 'max' => 255],
			[['name', 'password'], 'string', 'max' => 60],
			[['email'], 'unique'],
			[['name'], 'unique']
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'email' => 'Email',
			'name' => 'Name',
			'password' => 'Password',
			'role' => 'Role',
		];
	}




}
