<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "job".
 *
 * @property integer $id
 * @property integer $dept_id
 * @property integer $sequence
 * @property string $name
 * @property string $menuGroup
 * @property string $description
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property \common\models\ApplicationJob[] $applicationJobs
 * @property \common\models\Department $dept
 * @property string $aliasModel
 */
abstract class Job extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'job';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dept_id', 'sequence', 'name', 'menuGroup'], 'required'],
            [['dept_id', 'sequence'], 'integer'],
            [['description'], 'string'],
            [['name', 'menuGroup'], 'string', 'max' => 24],
            [['dept_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Department::className(), 'targetAttribute' => ['dept_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dept_id' => 'Dept ID',
            'sequence' => 'Sequence',
            'name' => 'Name',
            'menuGroup' => 'Menu Group',
            'description' => 'Description',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApplicationJobs()
    {
        return $this->hasMany(\common\models\ApplicationJob::className(), ['job_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDept()
    {
        return $this->hasOne(\common\models\Department::className(), ['id' => 'dept_id']);
    }




}
