<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mmf_menu_group".
 *
 * @property integer $id
 * @property integer $sequence
 * @property string $name
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\Job[] $jobs
 * @property string $aliasModel
 */
abstract class MenuGroup extends \yii\db\ActiveRecord
{



	/**
	 * @inheritdoc
	 */
	public static function tableName()
	{
		return 'mmf_menu_group';
	}


	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			[
				'class' => TimestampBehavior::className(),
			],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['sequence', 'name'], 'required'],
			[['sequence'], 'integer'],
			[['name'], 'string', 'max' => 24]
		];
	}

	/**
	 * @inheritdoc
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'sequence' => 'Sequence',
			'name' => 'Name',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getJobs()
	{
		return $this->hasMany(\common\models\Job::className(), ['group_id' => 'id']);
	}




}
