<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "Profile".
 *
 * @property integer $id
 * @property string $givenName
 * @property string $familyName
 * @property string $preferredName
 * @property string $email
 * @property string $phone1
 * @property string $phone2
 * @property string $address1
 * @property string $address2
 * @property string $locality
 * @property string $state
 * @property string $postcode
 * @property string $country
 * @property string $emergencyContact
 * @property string $emergencyPhone1
 * @property string $emergencyPhone2
 * @property integer $rsa
 * @property integer $dl_c
 * @property integer $dl_h
 * @property integer $cse
 * @property integer $ohs
 * @property integer $vol
 * @property integer $mmfVol
 * @property integer $mmfAtt
 * @property string $discovery
 * @property string $discoveryDetail
 * @property string $created
 * @property integer $createdBy
 * @property string $updated
 * @property integer $updatedBy
 * @property string $aliasModel
 */
abstract class Profile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Profile';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'createdBy',
                'updatedByAttribute' => 'updatedBy',
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'updated',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['givenName', 'familyName', 'email', 'locality', 'emergencyContact', 'emergencyPhone1'], 'required'],
            [['rsa', 'dl_c', 'dl_h', 'cse', 'ohs', 'vol', 'mmfVol', 'mmfAtt'], 'integer'],
            [['givenName', 'familyName', 'preferredName', 'country'], 'string', 'max' => 32],
            [['email', 'locality', 'emergencyContact'], 'string', 'max' => 64],
            [['phone1', 'phone2', 'emergencyPhone1', 'emergencyPhone2', 'discovery'], 'string', 'max' => 24],
            [['address1', 'address2', 'discoveryDetail'], 'string', 'max' => 255],
            [['state'], 'string', 'max' => 16],
            [['postcode'], 'string', 'max' => 12]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'givenName' => 'Given Name',
            'familyName' => 'Family Name',
            'preferredName' => 'Preferred Name',
            'email' => 'Email',
            'phone1' => 'Phone1',
            'phone2' => 'Phone2',
            'address1' => 'Address1',
            'address2' => 'Address2',
            'locality' => 'Locality',
            'state' => 'State',
            'postcode' => 'Postcode',
            'country' => 'Country',
            'emergencyContact' => 'Emergency Contact',
            'emergencyPhone1' => 'Emergency Phone1',
            'emergencyPhone2' => 'Emergency Phone2',
            'rsa' => 'Rsa',
            'dl_c' => 'Dl C',
            'dl_h' => 'Dl H',
            'cse' => 'Cse',
            'ohs' => 'Ohs',
            'vol' => 'Vol',
            'mmfVol' => 'Mmf Vol',
            'mmfAtt' => 'Mmf Att',
            'discovery' => 'Discovery',
            'discoveryDetail' => 'Discovery Detail',
            'created' => 'Created',
            'createdBy' => 'Created By',
            'updated' => 'Updated',
            'updatedBy' => 'Updated By',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProfileQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProfileQuery(get_called_class());
    }


}
