<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "mmf_update".
 *
 * @property integer $id
 * @property string $email
 * @property string $name
 * @property string $other0
 * @property string $other1
 * @property string $other2
 * @property integer $status0
 * @property integer $status1
 * @property integer $status2
 * @property string $aliasModel
 */
abstract class Update extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mmf_update';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'name'], 'required'],
            [['status0', 'status1', 'status2'], 'integer'],
            [['email', 'other0', 'other1', 'other2'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 60],
            [['email'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'name' => 'Name',
            'other0' => 'Other0',
            'other1' => 'Other1',
            'other2' => 'Other2',
            'status0' => 'Status0',
            'status1' => 'Status1',
            'status2' => 'Status2',
        ];
    }




}
