<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var common\models\Application $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="application-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Application',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute user_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'user_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Profile::find()->all(), 'user_id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
    ]
); ?>

<!-- attribute job_choice_1 -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_1')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_1'])),
    ]
); ?>

<!-- attribute year -->
			<?= $form->field($model, 'year')->textInput(['maxlength' => true]) ?>

<!-- attribute availableFromDate -->
			<?= $form->field($model, 'availableFromDate')->textInput(['maxlength' => true]) ?>

<!-- attribute availableFromTime -->
			<?= $form->field($model, 'availableFromTime')->textInput() ?>

<!-- attribute availableToDate -->
			<?= $form->field($model, 'availableToDate')->textInput(['maxlength' => true]) ?>

<!-- attribute availableToTime -->
			<?= $form->field($model, 'availableToTime')->textInput() ?>

<!-- attribute job_choice_2 -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_2')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_2'])),
    ]
); ?>

<!-- attribute job_choice_3 -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'job_choice_3')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Job::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['job_choice_3'])),
    ]
); ?>

<!-- attribute bestTime -->
			<?= $form->field($model, 'bestTime')->textInput() ?>

<!-- attribute double -->
			<?= $form->field($model, 'double')->textInput() ?>

<!-- attribute status -->
			<?= $form->field($model, 'status')->textInput() ?>

<!-- attribute team_id -->
			<?= $form->field($model, 'team_id')->textInput() ?>

<!-- attribute availabilityNotes -->
			<?= $form->field($model, 'availabilityNotes')->textarea(['rows' => 6]) ?>

<!-- attribute otherNotes -->
			<?= $form->field($model, 'otherNotes')->textarea(['rows' => 6]) ?>

<!-- attribute rejectedReason -->
			<?= $form->field($model, 'rejectedReason')->textarea(['rows' => 6]) ?>

<!-- attribute referee -->
			<?= $form->field($model, 'referee')->textInput(['maxlength' => true]) ?>

<!-- attribute refereeRelationship -->
			<?= $form->field($model, 'refereeRelationship')->textInput(['maxlength' => true]) ?>

<!-- attribute refereePhone -->
			<?= $form->field($model, 'refereePhone')->textInput(['maxlength' => true]) ?>

<!-- attribute bestCallingTime -->
			<?= $form->field($model, 'bestCallingTime')->textInput(['maxlength' => true]) ?>

<!-- attribute volunteerName -->

<!-- attribute preferredName -->

<!-- attribute jobPreference1 -->

<!-- attribute jobPreference2 -->

<!-- attribute jobPreference3 -->

<!-- attribute availableFrom -->

<!-- attribute availableTo -->

<!-- attribute earlyLate -->

<!-- attribute returned -->
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'Application'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

